export interface EnvConfigInterface {
	PORT_AUTH_SERVICE: string
	JWT_REFRESH_SECRET: string
	GOOGLE_CLIENT_ID: string
	GOOGLE_CLIENT_SECRET: string
	GMAIL_APP_PASSWORD: string
	COOKIE_SECRET: string
	FRONTEND_URL: string
	GMAIL_USER: string
	REDIRECT_URI: string
	AUTH_URL: string
	TOKEN_URL: string
	USER_INFO_URL: string
	JWT_SECRET_PRIVATE_KEY: string
	JWT_SECRET_PUBLIC_KEY: string
	INTERNAL_KEY_SECRET: string
	CREDITS_SERVICE_URL: string
	LISTINGS_SERVICE_URL: string
	RESERVATION_SERVICE_URL: string
}
